# Generated by Django 4.1.2 on 2023-11-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_ans_count_alter_question_cur_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')]),
        ),
    ]
