# Generated by Django 4.1.2 on 2023-11-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tag_uses_alter_question_ans_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateToAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RateToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
